providers = ["...", "node"]

[phases.setup]
nixPkgs = ["python3", "poetry"]
aptPkgs = [
    "libstdc++6",
]
nodeVersion = "18"

[start]
cmd = "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"

[phases.runtime]
aptPkgs = ["libstdc++6"]

