providers = ["...", "node"]

[phases.setup]
nixPkgs = ["python3", "poetry", "nodejs_20"]
aptPkgs = [
    "libstdc++6",
    "libgomp1",  # OpenMP runtime for PyTorch
    "libgcc-s1", # GCC support library
    "zlib1g",    # Required by many Python packages
    "libblas3",  # Required for numerical operations
    "liblapack3" # Required for numerical operations
]

[start]
cmd = "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"

[phases.runtime]
aptPkgs = [
    "libstdc++6",
    "libgomp1",
    "libgcc-s1",
    "zlib1g",
    "libblas3",
    "liblapack3"
]

