providers = ["...", "node"]

[phases.setup]
nixPkgs = ["python3", "poetry", "nodejs_20"]
aptPkgs = ["libstdc++6"]

[start]
cmd = "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"

# Add this section to ensure runtime dependencies are included
[phases.runtime]
aptPkgs = ["libstdc++6"]

