providers = ["...", "python", "node"]

[phases.setup]
nixPkgs = ["python3", "poetry"]

[phases.install]
cmds = ["poetry install --no-dev --no-interaction --no-ansi"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"